version: '1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
  app:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/src/goprograms/auth
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db